### ISSUE TITLE
memo

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/dotfiles.win#3]
気づいたことなど

**Comment by ys-nuem** [comment]
### Cygwin/MSYS2 におけるシンボリックリンクの挙動について

* Cygwin で `winsymlinks:*` 無しでシンボリックリンクを作成すると，リンク先情報が記載されたシステムファイル（システムファイル属性付きのファイル）が生成される．

* MSYS2 で `winsymlinks:*` 無しでシンボリックリンクを作成すると，元ファイル／ディレクトリがコピーされる．

* `winsymlinks:lnk` , `winsymlinks:native{,strict}` の挙動はCygwin, MSYS2 で同じ（多分）

* MSYS2で`winsymlinks` 無しで作成したもの以外はすべてCygwin,MSYS2双方でシンボリックリンクとして認識される
  - `winsymlinks` の値が一致している必要はない

**Comment by ys-nuem** [comment]
#memo [ghq][dotfiles]

MSYS2のホームディレクトリ($HOME)とWindowsのホームディレクトリ(%USERPROFILE%) が異なる場合，
ghqのディレクトリが `%USERPROFILE%/.ghq`にならないようにするためには `.gitconfig` に相対パスで記述する:

```gitconfig
...
[ghq]
  root = .ghq  # <= ~/.ghq とは記述しないこと
```

**Comment by ys-nuem** [comment]
`ghq look [repo]` はシェルではなくコマンドプロンプトが起動する

**Comment by ys-nuem** [comment]
### nvm-windows による NodeJSインストール方法

1. `$HOME/.nvm` に `nvm-noinstall.zip` 下を展開
1. 以下の環境変数を windows 側か `zshrc` に記述する
  * `NVM_HOME=$HOME/.nvm`
    - nvm 本体が格納される
  * `NVM_SYMLINK=$HOME/.nvm/nodejs` 
    - アクティブなバージョンのnodejs へのシンボリックリンクが張られる）

1. `$NVM_HOME/settings.txt` に以下を保存する

  ```txt
  root: $HOME\.nvm 
  path: $HOME\.nvm\nodejs 
  arch: 64 
  proxy: none
  ```

---

* npm でインストールしたパッケージは `$NVM_SYMLINK/node_modules` 下にインストールされる
* 各 nodejs のグローバル設定ファイルは `$NVM_SYMLINK/etc/npmrc` に置ける
  - インストール先は `prefix = $HOME/.npm` で変更できる ?

**Comment by ys-nuem** [comment]
## Git for Windows におけるシンボリックリンク周りの挙動

* シンボリックリンクを登録しようとすると失敗（`unlink(): undefined` 的なメッセージが表示される）

## MSYS2版 Git におけるシンボリック周りの挙動

* シェル内でシンボリックリンクとして認識するものはすべてシンボリックリンクとしてステージングされる
  - Cygwin のシンボリックリンク (`CYGWIN= ln -s hoge.txt a`)
  - ショートカット形式 (`MSYS=winsymlinks:lnk ln -s hoge.txt b`)
  - Windowsのシンボリックリンク (`MSYS=winsymlinks:native ln -s hoge.txt c`)

* チェックアウト時の挙動がおかしい
  - `MSYS=` `MSYS=winsymlinks:lnk` `MSYS=winsymlinks:native` いずれの場合においても，リンク先のパスが記述されたテキストファイルに変換される

* クローン時の挙動 (cygwin)
  - `CYGWIN=` では Cygwin 形式
  - `CYGWIN=winsymlinks:lnk` ではショートカット
  - `CYGWIN=winsymlinks:native` では Cygwin 形式（ネイティブのリンク作成に失敗？）
  - `CYGWIN=winsymlinks:nativestrict` ではリンク先のパスが記述されたテキストファイル

* クローン次の挙動 (MSYS2)
  - `MSYS=winsymlinks:lnk` ではショートカット
  - `MSYS=`, `MSYS=winsymlinks:native{,strict}` ではリンク先のパスが記述されたテキストファイル

**Comment by ys-nuem** [comment]
* `core.symlinks = false` のとき，シンボリックリンクがファイルとしてチェックアウトされる
* `MSYS=winsymlinks:lnk` のとき，cloneしたリポジトリの `core.symlinks` は自動で `true` になる
* `MSYS=winsymlinks:nativestrict` のとき，`core.symlinks`は __自動で`false`になる__

**Comment by ys-nuem** [comment]
* シンボリックリンク作成可能な状態，かつ Git for Windows であれば 正常にチェックアウトできる
  - グローバルの `core.symlinks` 属性をただしく継承する

---

* シンボリックリンクを使用しない
* git add 時のみ Cygwin 版の Git を使う
* シンボリックリンク用のコマンドを別途用意する

**Comment by ys-nuem** [comment]
`core.symlink=true` であれば Git for WIndows でもただしくチェックインできた
